url: "https://thinkforward.academy"
permalink: simple
timezone: America/Los_Angeles
template_engine: serbea

collections:
  book:
    output: true
    permalink: "/:collection/:path/"
    sort_by: order
    name: Book
  posts:
    output: true
    permalink: "/:collection/:path/"
    sort_by: order
    name: Posts
  quotes:
    output: false
    permalink: "/:collection/:path/"
    sort_by: order
    name: Quotes
  music:
    output: true
    permalink: "/:collection/:path/"
    sort_by: order
    name: Music

pagination:
  enabled: true

html_inspector_parser: nokolexbor

# Environment-specific settings
development:
  unpublished: true
